import static com.kms.katalon.core.checkpoint.CheckpointFactory.findCheckpoint
import static com.kms.katalon.core.testcase.TestCaseFactory.findTestCase
import static com.kms.katalon.core.testdata.TestDataFactory.findTestData
import static com.kms.katalon.core.testobject.ObjectRepository.findTestObject
import static com.kms.katalon.core.testobject.ObjectRepository.findWindowsObject
import com.kms.katalon.core.checkpoint.Checkpoint as Checkpoint
import com.kms.katalon.core.cucumber.keyword.CucumberBuiltinKeywords as CucumberKW
import com.kms.katalon.core.mobile.keyword.MobileBuiltInKeywords as Mobile
import com.kms.katalon.core.model.FailureHandling as FailureHandling
import com.kms.katalon.core.testcase.TestCase as TestCase
import com.kms.katalon.core.testdata.TestData as TestData
import com.kms.katalon.core.testng.keyword.TestNGBuiltinKeywords as TestNGKW
import com.kms.katalon.core.testobject.TestObject as TestObject
import com.kms.katalon.core.webservice.keyword.WSBuiltInKeywords as WS
import com.kms.katalon.core.webui.keyword.WebUiBuiltInKeywords as WebUI
import com.kms.katalon.core.windows.keyword.WindowsBuiltinKeywords as Windows
import internal.GlobalVariable as GlobalVariable
import org.openqa.selenium.Keys as Keys

TestData ParamDB = findTestData('Data Files/Param MO MAP')
TestData Hohendy = findTestData('Data Files/Param Pengajuan')
TestData Dataparampemohon = findTestData('Data Files/Param Pemohon')

//Mobile.startExistingApplication('id.co.jmpmf.jmo3')

//for (int baris = 1; baris <= Hohendy.getRowNumbers(); baris++)
//{
//	if (Hohendy.getValue('Use', baris) == 'Yes' && Hohendy.getValue('Tipe Produk', baris) == 'Used Bike')
//	{
		// KTP Debitur  Pasangan
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/KTP Debitur  Pasangan'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/ImageButton Foto'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Button - KTP DEBITUR  PASANGAN'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Capture photo from camera'), 0)
		Mobile.delay(1)
		Mobile.tapAtPosition(535, 1989, FailureHandling.OPTIONAL)
		Mobile.delay(3)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/TextView - OK'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Button - SIMPAN DATA'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Back'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		
		// AKTA NIKAH  CERAI, DOKUMEN PENJAMIN
		Mobile.tap(findTestObject('Object Repository/Foto CO/Akta/Akta Nikah  Cerai, Dokumen Penjamin'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/ImageButton Foto'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Button - KTP DEBITUR  PASANGAN'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Capture photo from camera'), 0)
		Mobile.delay(1)
		Mobile.tapAtPosition(535, 1989, FailureHandling.OPTIONAL)
		Mobile.delay(3)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/TextView - OK'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Button - SIMPAN DATA'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Back'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		
//		// FOTO DOMISILI
		Mobile.tap(findTestObject('Object Repository/Foto CO/Foto dom/Foto Domisili'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Foto dom/Button Tampak Depan Domisili'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/ImageButton Foto'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Button - KTP DEBITUR  PASANGAN'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Capture photo from camera'), 0)
		Mobile.delay(1)
		Mobile.tapAtPosition(535, 1989, FailureHandling.OPTIONAL)
		Mobile.delay(3)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/TextView - OK'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Button - SIMPAN DATA'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Back'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)

		Mobile.tap(findTestObject('Object Repository/Foto CO/Foto dom/Buton Tampak Samping Domisili'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/ImageButton Foto'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Button - KTP DEBITUR  PASANGAN'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Capture photo from camera'), 0)
		Mobile.delay(1)
		Mobile.tapAtPosition(535, 1989, FailureHandling.OPTIONAL)
		Mobile.delay(3)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/TextView - OK'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Button - SIMPAN DATA'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Back'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		
		Mobile.tap(findTestObject('Object Repository/Foto CO/Foto Dom2/Button Lingkungan Sekitar Domisili'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/ImageButton Foto'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Button - KTP DEBITUR  PASANGAN'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Capture photo from camera'), 0)
		Mobile.delay(1)
		Mobile.tapAtPosition(535, 1989, FailureHandling.OPTIONAL)
		Mobile.delay(3)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/TextView - OK'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Button - SIMPAN DATA'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Back'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		
		Mobile.tap(findTestObject('Object Repository/Foto CO/Foto Dom2/button Tampak Dalam Domisili'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/ImageButton Foto'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Button - KTP DEBITUR  PASANGAN'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Capture photo from camera'), 0)
		Mobile.delay(1)
		Mobile.tapAtPosition(535, 1989, FailureHandling.OPTIONAL)
		Mobile.delay(3)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/TextView - OK'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Button - SIMPAN DATA'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Back'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		
		// Bukti Kepemilikan Rumah
		Mobile.tap(findTestObject('Object Repository/Foto CO/BUKTI KEPEMLIKKAM RUMAH/Bukti Kepemilikan Rumah'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/ImageButton Foto'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Button - KTP DEBITUR  PASANGAN'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Capture photo from camera'), 0)
		Mobile.delay(1)
		Mobile.tapAtPosition(535, 1989, FailureHandling.OPTIONAL)
		Mobile.delay(3)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/TextView - OK'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Button - SIMPAN DATA'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Back'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		
		// Bukti Kapasitas
		Mobile.tap(findTestObject('Object Repository/Foto CO/Bukti/Bukti Kapasitas'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/ImageButton Foto'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Button - KTP DEBITUR  PASANGAN'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Capture photo from camera'), 0)
		Mobile.delay(1)
		Mobile.tapAtPosition(535, 1989, FailureHandling.OPTIONAL)
		Mobile.delay(3)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/TextView - OK'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Button - SIMPAN DATA'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Back'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)

		// FOTO Survie
		Mobile.tap(findTestObject('Object Repository/Foto CO/Survei/Foto Selfie Survei'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/ImageButton Foto'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Button - KTP DEBITUR  PASANGAN'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Capture photo from camera'), 0)
		Mobile.delay(1)
		Mobile.tapAtPosition(535, 1989, FailureHandling.OPTIONAL)
		Mobile.delay(3)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/TextView - OK'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Button - SIMPAN DATA'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Back'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
			
		Mobile.swipe(0, 900, 0, 0)
		
		// FPP
		Mobile.tap(findTestObject('Object Repository/Foto CO/FPP/FPP'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/ImageButton Foto'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Button - KTP DEBITUR  PASANGAN'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/Capture photo from camera'), 0)
		Mobile.delay(1)
		Mobile.tapAtPosition(535, 1989, FailureHandling.OPTIONAL)
		Mobile.delay(3)
		Mobile.tap(findTestObject('Object Repository/Foto CO/KTP/TextView - OK'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Button - SIMPAN DATA'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/Back'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		Mobile.delay(1)
		Mobile.tap(findTestObject('Object Repository/Form Upload 2/Upload 2/ImageButton Back 2'), 0)
		
Mobile.tap(findTestObject('Object Repository/Foto CO/Button simpan/KIRIM'), 0)



